// automatically generated by the FlatBuffers compiler, do not modify

package com.qbao.im.api.common.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Message extends Table {
  public static Message getRootAsMessage(ByteBuffer _bb) { return getRootAsMessage(_bb, new Message()); }
  public static Message getRootAsMessage(ByteBuffer _bb, Message obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Message __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public int netId() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String self() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer selfAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String dest() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer destAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public String content() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public String platform() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer platformAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public String version() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer versionAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public int status() { int o = __offset(18); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createMessage(FlatBufferBuilder builder,
      int userIdOffset,
      int netId,
      int selfOffset,
      int destOffset,
      int contentOffset,
      int platformOffset,
      int versionOffset,
      int status) {
    builder.startObject(8);
    Message.addStatus(builder, status);
    Message.addVersion(builder, versionOffset);
    Message.addPlatform(builder, platformOffset);
    Message.addContent(builder, contentOffset);
    Message.addDest(builder, destOffset);
    Message.addSelf(builder, selfOffset);
    Message.addNetId(builder, netId);
    Message.addUserId(builder, userIdOffset);
    return Message.endMessage(builder);
  }

  public static void startMessage(FlatBufferBuilder builder) { builder.startObject(8); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(0, userIdOffset, 0); }
  public static void addNetId(FlatBufferBuilder builder, int netId) { builder.addInt(1, netId, 0); }
  public static void addSelf(FlatBufferBuilder builder, int selfOffset) { builder.addOffset(2, selfOffset, 0); }
  public static void addDest(FlatBufferBuilder builder, int destOffset) { builder.addOffset(3, destOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(4, contentOffset, 0); }
  public static void addPlatform(FlatBufferBuilder builder, int platformOffset) { builder.addOffset(5, platformOffset, 0); }
  public static void addVersion(FlatBufferBuilder builder, int versionOffset) { builder.addOffset(6, versionOffset, 0); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addInt(7, status, 0); }
  public static int endMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // userId
    return o;
  }
}

