// automatically generated by the FlatBuffers compiler, do not modify

package com.qbao.im.api.common.flatbuf;

public final class MSGSTATUS {
  private MSGSTATUS() { }
  public static final int SERVER_RECEIVER = 0;
  public static final int SERVER_SEND = 1;
  public static final int CLIENT_RECEIVER = 2;
  public static final int CLIENT_SEND = 3;

  public static final String[] names = { "SERVER_RECEIVER", "SERVER_SEND", "CLIENT_RECEIVER", "CLIENT_SEND", };

  public static String name(int e) { return names[e]; }
}

